
# LOLBAS: WFMFormat.exe — Legitimate use: pretty-print dump files generated by the Message Farm Analyzer tool
# DEVELOPER-ONLY: Requires download of Message Farm Analyzer (microsoft.com/en-us/download/details.aspx?id=103244) and .NET Framework 3.5

"""
 Creates the autoIT stub code to be passed into the master compile

 Simulates legitimate developer/analyst use of WFMFormat.exe to format
 and pretty-print dump files generated by the Message Farm Analyzer tool.

 Requires the path to a dumpfile.txt produced by Message Farm Analyzer.
 WFMFormat.exe must be present in the specified tool directory.
 .NET Framework 3.5 must be installed on the target system.

 the master script will already define the typing speed as part of the master declarations
"""

__author__ = "Matt Lorentzen @lorentzenman"
__license__ = "MIT"


import cmd
import random
import textwrap

# Sheepl Class Imports
from utils.base.base_cmd_class import BaseCMD


class WfmFormat(BaseCMD):
    """
    # LOLBAS: WFMFormat.exe — Legitimate use: pretty-print dump files generated by the Message Farm Analyzer tool

    Inherits from BaseCMD
        This parent class contains:
        : do_back               > return to main menu
        : do_discard            > discard current task
        : do_complete           > completes the task and resets trackers
        : check_task_started    > checks to see task status
    """

    def __init__(self, csh, cl):

        # Calling super to inherit from the BaseCMD Class __init__
        super(WfmFormat, self).__init__(csh, cl)

        # Override the defined task name
        self.taskname = 'WfmFormat'

        # current Sheepl Object
        self.csh = csh
        # current colour object
        self.cl = cl

        # Overrides Base Class Prompt Setup
        if csh.creating_subtasks:
            self.baseprompt = cl.yellow('[>] Creating subtask\n{} > wfmformat >: '.format(csh.name.lower()))
        else:
            self.baseprompt = cl.yellow('{} > wfmformat >: '.format(csh.name.lower()))

        self.prompt = self.baseprompt

        # Path to the directory containing WFMFormat.exe
        self.tool_dir = None
        # Path to the dumpfile.txt to format
        self.dump_file = None

        self.indent_space = '    '

        self.introduction = """
        ----------------------------------
        [!] WfmFormat Interaction.
        [!] DEVELOPER-ONLY: Requires Message Farm Analyzer download and .NET Framework 3.5.
        Type help or ? to list commands.
        1: Start a new block using 'new'
        2: Set the tool directory using 'tool_dir <path>'
        3: Optionally set a dump file path using 'dump_file <path>'
        4: Complete the interaction using 'complete'
        """

        # ----------------------------------- >
        # now call the loop if we are in interactive mode by checking
        # if we are parsing JSON

        if not self.csh.json_parsing:
            # call the intro and then start the loop
            print(textwrap.dedent(self.introduction))
            self.cmdloop()


    #######################################################################
    #  WfmFormat Console Commands
    #######################################################################


    def do_new(self, arg):
        """
        This command creates a new WfmFormat interaction block
        """
        # Init tracking booleans
        # method from parent class BaseCMD
        if self.check_task_started():
            self.prompt = self.cl.blue("[*] Current Task : 'WfmFormat_{}'".format(str(self.csh.counter.current())) + "\n" + self.baseprompt)


    def do_tool_dir(self, tool_dir):
        """
        Set the directory path containing WFMFormat.exe.
        Example: tool_dir C:\\Tools\\MessageFarmAnalyzer
        """
        if tool_dir:
            if self.taskstarted:
                self.tool_dir = tool_dir.strip()
                print(self.cl.green("[*] Tool directory set to: {}".format(self.tool_dir)))
            else:
                print(self.cl.red("[!] <ERROR> You need to start a new WfmFormat Interaction."))
                print(self.cl.red("[!] <ERROR> Start this with 'new' from the menu."))
        else:
            print(self.cl.red("[!] <ERROR> Please provide the tool directory path."))


    def do_dump_file(self, dump_file):
        """
        Optionally set the path to a dumpfile.txt to format.
        If not set, WFMFormat.exe looks for dumpfile.txt in the current working directory.
        Example: dump_file C:\\Logs\\dumpfile.txt
        """
        if dump_file:
            if self.taskstarted:
                self.dump_file = dump_file.strip()
                print(self.cl.green("[*] Dump file set to: {}".format(self.dump_file)))
            else:
                print(self.cl.red("[!] <ERROR> You need to start a new WfmFormat Interaction."))
                print(self.cl.red("[!] <ERROR> Start this with 'new' from the menu."))
        else:
            print(self.cl.red("[!] <ERROR> Please provide the dump file path."))


    def do_assigned(self, arg):
        """
        Get the current assigned WfmFormat configuration
        """
        print(self.cl.green("[?] Currently Assigned WfmFormat Configuration"))
        print("[>] Tool Directory : {}".format(self.tool_dir if self.tool_dir else "(not set)"))
        print("[>] Dump File      : {}".format(self.dump_file if self.dump_file else "(not set — uses dumpfile.txt in tool directory)"))


    def do_complete(self, arg):
        """
        This command calls the constructor on the AutoITBlock
        with all the specific arguments
        >> Check the AutoIT constructor requirements
        """

        if self.taskstarted:
            if not self.tool_dir:
                print(self.cl.red("[!] <ERROR> tool_dir must be set before completing."))
                return
            self.create_autoIT_block()

        # now reset the tracking values and prompt
        self.complete_task()

        # reset task-specific state for the next interaction
        self.tool_dir = None
        self.dump_file = None


    ######################################################################
    # WfmFormat AutoIT Block Definition
    #######################################################################


    def create_autoIT_block(self):
        """
        Creates the AutoIT Script Block
        csh.add_tasks takes two positional arguments
            commandname_{counter}, and task
        """

        current_counter = str(self.csh.counter.current())
        self.csh.add_task('WfmFormat_' + current_counter, self.create_autoit_function())


    def create_autoit_function(self):
        """
        Grabs all the output from the respective functions and builds the AutoIT output
        """

        autoIT_script = (
            self.autoit_function_open() +
            self.open_commandshell() +
            self.text_typing_block() +
            self.close_function()
        )

        return autoIT_script


    def parse_json_profile(self, **kwargs):
        """
        Takes kwargs in and builds out task variables when using JSON profiles.
        This function sets the various object attributes in the same way
        that the interactive mode does.

        Required JSON keys:
            tool_dir  : str — directory containing WFMFormat.exe

        Optional JSON keys:
            dump_file : str — path to dumpfile.txt to format;
                              if absent, WFMFormat.exe uses dumpfile.txt in tool_dir
        """

        print("[%] Setting attributes from JSON Profile")
        print(f"[-] The following keys are needed for this task : {[x for x in list(kwargs.keys())[1:]]}")

        self.tool_dir = kwargs.get("tool_dir", None)
        if self.tool_dir:
            print(f"[*] Setting tool_dir attribute : {self.tool_dir}")
        else:
            print("[!] <ERROR> tool_dir is required for WfmFormat.")
            return

        self.dump_file = kwargs.get("dump_file", None)
        if self.dump_file:
            print(f"[*] Setting dump_file attribute : {self.dump_file}")
        else:
            print("[*] No dump_file provided — will rely on dumpfile.txt in tool directory")

        # once these have all been set in here, then self.create_autoIT_block() gets called which pushes the task on the stack
        self.create_autoIT_block()


    # --------------------------------------------------->
    # Create Open Block


    def autoit_function_open(self):
        """
        Initial Entrypoint Definition for AutoIT function
        """

        fn = """
        ; < ----------------------------------- >
        ; <      WfmFormat Interaction
        ; < ----------------------------------- >

        """
        if not self.csh.creating_subtasks:
            fn += "WfmFormat_{}()".format(self.csh.counter.current())

        return textwrap.dedent(fn)


    # --------------------------------------------------->
    # Define AutoIT Function

    def open_commandshell(self):
        """
        Opens a CMD shell via Win+R run dialogue
        """

        _open_commandshell = """

        Func WfmFormat_{}()

            ; Creates a WfmFormat Interaction via CMD

            Send("#r")
            ; Wait 10 seconds for the Run dialogue window to appear.
            WinWaitActive("Run", "", 10)
            ; note this needs to be escaped
            Send('cmd{}')
            ; check to see if we are already in an RDP session
            $active_window = _WinAPI_GetClassName(WinGetHandle("[ACTIVE]"))
            ConsoleWrite($active_window & @CRLF)
            $inRDP = StringInStr($active_window, "TscShellContainerClass")
            ; if the result is greater than 1 we are inside an RDP session
            if $inRDP < 1 Then
                WinWaitActive("[CLASS:ConsoleWindowClass]", "", 10)
                SendKeepActive("[CLASS:ConsoleWindowClass]")
            EndIf


        """.format(self.csh.counter.current(), "{ENTER}")

        return textwrap.dedent(_open_commandshell)


    # --------------------------------------------------->
    # Typing Output

    def text_typing_block(self):
        """
        Builds the WFMFormat commands to type into the CMD window.
        Changes directory to the tool location, then runs WFMFormat.exe
        optionally copying a specified dump file first.
        """
        typing_text = '\n'

        # Change to the directory containing WFMFormat.exe
        cd_cmd = 'cd /d {}'.format(self.tool_dir)
        typing_text += 'Send("' + self._escape_send(cd_cmd) + '{ENTER}")\n'
        typing_text += 'sleep({})\n'.format(random.randint(2000, 5000))

        # If a specific dump file was provided, copy it into the tool directory
        if self.dump_file:
            copy_cmd = 'copy /Y {} dumpfile.txt'.format(self.dump_file)
            typing_text += 'Send("' + self._escape_send(copy_cmd) + '{ENTER}")\n'
            typing_text += 'sleep({})\n'.format(random.randint(1000, 3000))

        # Run WFMFormat.exe — it reads dumpfile.txt from the current directory
        typing_text += 'Send("' + self._escape_send('WFMFormat.exe') + '{ENTER}")\n'
        typing_text += 'sleep({})\n'.format(random.randint(2000, 5000))

        typing_text += "Send('exit{ENTER}')\n"
        typing_text += "; Reset Focus\n"
        typing_text += 'SendKeepActive("")'

        return textwrap.indent(typing_text, self.indent_space)


    # --------------------------------------------------->
    # Close AutoIT Function

    def close_function(self):
        """
        Closes the WfmFormat AutoIT function declaration
        """

        end_func = """

        EndFunc

        """

        return textwrap.dedent(end_func)
